stages:
#  - test
  - deploy
  - envoy_check
  - rollback

#tests:
#  stage: test
#  script:
#    - cd $DEPLOY_DIR
#    - bash ./scripts/test.sh
#  only:
#    - master

deploy:
  stage: deploy
  script:
    - cd $DEPLOY_DIR
    - bash ./scripts/deploy.sh
    - '[ "$(sudo docker ps -q -f name=blue)" ] && sudo docker exec blue php /var/www/html/vendor/bin/envoy run optimize'
    - '[ "$(sudo docker ps -q -f name=green)" ] && sudo docker exec green php /var/www/html/vendor/bin/envoy run optimize'
  when: manual

envoy_check:
  stage: envoy_check
  environment:
    name: production
  script:
    - '[ "$(sudo docker ps -q -f name=blue)" ] && sudo docker exec --user root blue php /var/www/html/vendor/bin/envoy run check'
    - '[ "$(sudo docker ps -q -f name=green)" ] && sudo docker exec --user root green php /var/www/html/vendor/bin/envoy run check'
  when: manual

rollback:
  stage: rollback
  script:
    - cd $DEPLOY_DIR
    - bash ./scripts/rollback.sh
    - '[ "$(sudo docker ps -q -f name=blue)" ] && sudo docker exec blue php /var/www/html/vendor/bin/envoy run optimize'
    - '[ "$(sudo docker ps -q -f name=green)" ] && sudo docker exec green php /var/www/html/vendor/bin/envoy run optimize'
  when: manual
