@host=http://localhost
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS92MS9yZWZyZXNoIiwiaWF0IjoxNzUyNTAwNDAyLCJleHAiOjE3NTI1MDEwMDIsIm5iZiI6MTc1MjUwMDQwMiwianRpIjoiNGt4S1I2WnJpNTdvRGptZiIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3IiwiYWRtaW4iOnRydWUsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJuYW1lIjoiYWRtaW4ifQ.7r7OM5YtoRQB57gcj3wE48GU_1g9z7KlZo3dUQFYWfI

POST {{host}}/api/v1/login
Content-Type: application/json
Accept: application/json

{
    "email": "admin@example.com",
    "password": "password"
}

###

POST {{host}}/api/v1/refresh
Content-Type: application/json
Accept: application/json

{
    "refresh_token": "uqKPc2a8KvQ2zJZnCB4avLKaRyafEV9fmgFgRS2otyHxqCENBakOAX40x5KqtDPV"
}

###

POST {{host}}/api/v1/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "refresh_token": "CM9L9m88nwC4rWiiLhxexTIz8f5btugud5fDtRHlSuZBhksb6BpIJitWfHl2zwU1"
}

###
