@host=http://localhost
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS92MS9yZWZyZXNoIiwiaWF0IjoxNzUyMDYzNTg2LCJleHAiOjE3NTIwNjcxODYsIm5iZiI6MTc1MjA2MzU4NiwianRpIjoiU3dJZ0lobnFhdERPYURKQSIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3IiwiYWRtaW4iOnRydWUsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJuYW1lIjoiYWRtaW4ifQ.MAxPDYcJCGHH3Hc3dfynfuWtiLfy3APDgsES71GWOwM

GET {{host}}/api/v1/news
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


###

GET {{host}}/api/v1/news/33
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{host}}/api/v1/news
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "title": "Заголовок новости 555",
    "content": "Тест новости",
    "author_id": 3,
    "category_id": 2,
    "published_at": "2025-07-20T14:47",
    "is_draft":  false
}

###

PUT {{host}}/api/v1/news/33
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "title": "Заголовок новости 5555",
    "content": "Тест новости",
    "author_id": 2,
    "category_id": 2,
    "published_at": "2025-07-20T14:47",
    "is_draft":  false
}

###

DELETE {{host}}/api/v1/news/32
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
