; Enable xdebug extension module
zend_extension=xdebug.so
max_execution_time=1000
max_input_time=1000
xdebug.client_host=host.docker.internal
xdebug.mode=develop,debug,coverage
xdebug.start_with_request=trigger
xdebug.log="/var/www/html/common/runtime/logs/xdebug.log"
